### ISSUE TITLE
Support for d3 v4

### ISSUE THREAD

**Issue by ramnathv** [DarkMarmot/kodama#15]
The breaking changes in d3 v4 break kodama as well. Is it possible to update kodama to support d3 v4?

**Comment by DarkMarmot** [comment]
Yes! We were just about to make the switch at work to d3v4 so it's been on my todo list -- but if you're looking to use it there, I'll make sure it's my first v4 project :)

**Comment by ramnathv** [comment]
Thanks @DarkMarmot I will go through the code base to see if I can help make meaningful contributions :)

**Comment by DarkMarmot** [comment]
Just wanted to let you know that one of my new co-workers added a PR that should provide d3.v4 support for kodama v2.0.0+. Hopefully no issues! :)
