### ISSUE TITLE
Display tooltip at a different target

### ISSUE THREAD

**Issue by ramnathv** [DarkMarmot/kodama#2]
While using voronoi paths with `d3`, I often want the tooltip trigger to happen on mousing over a voronoi path, but want the tooltip to be displayed on the underlying circle or line element. Is this possible with `d3.kodama`? I don't see anything in the current API that allows me to position the tooltip at an alternate target.

**Comment by DarkMarmot** [comment]
It was originally written to just track with the mouse, but I'll experiment with adding a target property to the api! Thanks for the suggestion!

**Comment by ramnathv** [comment]
Thanks for being so responsive! I am going through your code, but it will be a white before I can start making meaningful contributions :)

**Comment by DarkMarmot** [comment]
It's exciting for me to have a user outside my own company! And the code needs some better names for some variables and a LOT more comments probably (it's not set up well for others to easily read yet...) 
But I would love contributions! I've been trying to get into open source recently -- starting with this small tooltip library, then the much more involved message bus library already posted but needing much more explanation (https://github.com/DarkMarmot/catbus) and lastly I'm trying to launch a full javascript framework that I've been using for building data visualization dashboards. The last one is really big so I'm trying to learn how to release things with these smaller projects first...

**Comment by ramnathv** [comment]
Sounds great. I work on data visualization myself. So I will look forward to your dashboarding framework as well.

**Comment by timelyportfolio** [comment]
@ramnathv  should I assume you are working on an htmlwidget for this?

**Comment by ramnathv** [comment]
@timelyportfolio I see this more as a component that I would use in d3 based widgets. So not working on a standalone `htmlwidget` for this at the moment. @DarkMarmot for your reference, [htmlwidgets](http://htmlwidgets.org) is a framework and an R package that allows one to write R bindings to javascript visualization libraries.

**Comment by DarkMarmot** [comment]
thanks for the info! -- I've not used R before, but would love supporting it that way. I come from a math/programming background, but avoided statistics in school when I could.... about to push some new API features to place tips at a target :)

**Comment by DarkMarmot** [comment]
pushed version 1.4 with 'target' and 'by' methods, also added a 'white_wolf' theme as an example (since i had some bugs in my theme stuff and needed to validate it...) please let me know if it works well for you! :)

**Comment by ramnathv** [comment]
I am unable to get the `target` feature working. I am trying to display the tooltip on a `circle` element and I get the following error

```
Uncaught TypeError: target.getBoundingClientRect is not a function
```

**Comment by DarkMarmot** [comment]
Hmm -- I tested using it with nodes where I didn't have to use a voronoi layout to hop through -- i will try modifying your example and see if i can figure out a good way to do it or if i need to change something to make it easier to do.... the 'target' variable should be a dom node when getBoundingClientRect is called... hmm....

**Comment by DarkMarmot** [comment]
Here's the jsfiddle with the target working -- i added some comments in CAPS to make it easy to see where i made changes.

http://jsfiddle.net/su9qw647/1/

there are a couple issues i need to fix -- distance 0 doesn't work and gravity 'center' tries to avoid covering stuff up.... but if you note, i grab the node of the circle in the selection and add it as a target prop in the data. then the tip format method pulls it back out.

**Comment by ramnathv** [comment]
Great! I will look at this and modify things to see if I am able to get rid of the error. Thanks again!

**Comment by ramnathv** [comment]
It works for me. The error I was making was using a `d3.select(...)` as target instead of `d3.select(...)[0]`. Maybe this should be clarified in the README or in an example.

I am also able to replicate the error with `distance: 0`. I am closing this issue, since you have already created new ones for each of these bugs.

Thanks again for the awesome work.

**Comment by DarkMarmot** [comment]
Thanks! :) What you did though was _supposed_ to be supported as well -- it should've grabbed the first node automatically for either a jquery or d3 selection -- my code failed somewhere.
